sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t ynsoo1225/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true ynsoo1225/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"